#!/usr/bin/env python3
"""Build single-column mobile homepages from the maintained desktop READMEs."""
from pathlib import Path
from urllib.parse import urlsplit
import re
import sys
from html import escape

ROOT = Path(__file__).resolve().parents[1]
LABELS = {
    'en': ('Mobile version', 'Desktop version'),
    'zh': ('手机版首页', '桌面版首页'),
    'tw': ('手機版首頁', '桌面版首頁'),
    'ja': ('モバイル版', 'デスクトップ版'),
    'ko': ('모바일 버전', '데스크톱 버전'),
    'id': ('Versi seluler', 'Versi desktop'),
    'it': ('Versione mobile', 'Versione desktop'),
    'pt': ('Versão móvel', 'Versão desktop'),
    'es': ('Versión móvil', 'Versión de escritorio'),
    'de': ('Mobile Ansicht', 'Desktop-Ansicht'),
    'ru': ('Мобильная версия', 'Версия для компьютера'),
    'fr': ('Version mobile', 'Version ordinateur'),
    'th': ('เวอร์ชันมือถือ', 'เวอร์ชันเดสก์ท็อป'),
    'vi': ('Bản di động', 'Bản máy tính'),
    'ar': ('نسخة الهاتف', 'نسخة الحاسوب'),
}

def filename(lang):
    return 'README.md' if lang == 'en' else f'README_{lang.upper()}.md'


def badge(label, kind):
    width = max(150, len(label) * 13 + 54)
    icon = ('<rect x="16" y="9" width="13" height="20" rx="3" fill="none" stroke="white" stroke-width="1.8"/><path d="M20 25h5" stroke="white"/>' if kind == 'mobile' else '<rect x="12" y="10" width="24" height="15" rx="2" fill="none" stroke="white" stroke-width="1.8"/><path d="M24 25v5m-7 0h14" stroke="white" stroke-width="1.8"/>')
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="40" viewBox="0 0 {width} 40"><rect x=".5" y=".5" width="{width-1}" height="39" rx="8" fill="#7309e8"/>{icon}<text x="{(width+38)/2}" y="26" text-anchor="middle" font-family="Arial,Noto Sans,sans-serif" font-size="15" font-weight="600" fill="white">{escape(label)}</text></svg>\n'


def mobile(source, lang):
    source = re.sub(r'<!-- DEVICE-VIEW:START -->.*?<!-- DEVICE-VIEW:END -->\s*', '', source, flags=re.S)
    # Mobile language links stay within mobile/; source material remains in the repo root.
    def relative(target):
        if urlsplit(target).scheme or target.startswith(('#', '/', '//')):
            return target
        if target.split('#')[0] in {filename(code) for code in LABELS}:
            return target
        return '../' + target
    source = re.sub(r'(href|src)="([^"]+)"', lambda m: f'{m[1]}="{relative(m[2])}"', source)
    source = re.sub(r'(\]\()([^\s)]+)(\))', lambda m: m[1] + relative(m[2]) + m[3], source)
    # Each illustrated card becomes its own full-width block, retaining all links and alt text.
    def cards(match):
        cells = re.findall(r'<td\b[^>]*>(.*?)</td>', match[0], re.S)
        if not cells:
            return match[0]
        blocks = []
        for cell in cells:
            cell = re.sub(r'(<img\b[^>]*?)\swidth="[^"]+"', r'\1 width="100%"', cell)
            blocks.append(f'<p align="center">{cell}</p>')
        return '\n\n'.join(blocks)
    source = re.sub(r'<table\b.*?</table>', cards, source, flags=re.S)
    # Label comparison facts as stacked lines so no horizontal table is needed on a phone.
    def facts(match):
        lines = match[0].strip().splitlines()
        headers = [x.strip() for x in lines[0].strip('|').split('|')]
        blocks = []
        for row in lines[2:]:
            cells = [x.strip() for x in row.strip('|').split('|')]
            separator = '：' if lang in ('zh', 'tw', 'ja') else ':'
            blocks.append('\n'.join(f'- **{h}{separator}** {c}' for h, c in zip(headers, cells)))
        return '\n\n'.join(blocks) + '\n'
    source = re.sub(r'^\|[^\n]+\|\n\|[ :|\-]+\|\n(?:\|[^\n]+\|\n)+', facts, source, flags=re.M)
    switch = f'\n\n<!-- DEVICE-VIEW:START -->\n<p align="center"><a href="../{filename(lang)}"><img src="../assets/ui/desktop-{lang}.svg" height="40" alt="{LABELS[lang][1]}"></a></p>\n<!-- DEVICE-VIEW:END -->'
    source = source.replace('<!-- LANGUAGES:END -->', '<!-- LANGUAGES:END -->' + switch)
    return '<!-- Generated by scripts/build_mobile_readmes.py; edit the desktop README instead. -->\n' + source


def main():
    check = '--check' in sys.argv
    stale = []
    for lang, labels in LABELS.items():
        for kind, label in zip(('mobile', 'desktop'), labels):
            p = ROOT / f'assets/ui/{kind}-{lang}.svg'
            text = badge(label, kind)
            if check:
                if not p.exists() or p.read_text() != text:
                    stale.append(str(p.relative_to(ROOT)))
            else:
                p.write_text(text)
        p = ROOT / 'mobile' / filename(lang)
        text = mobile((ROOT / filename(lang)).read_text(), lang)
        if check:
            if not p.exists() or p.read_text() != text:
                stale.append(str(p.relative_to(ROOT)))
        else:
            p.parent.mkdir(exist_ok=True)
            p.write_text(text)
    if stale:
        raise SystemExit('Stale mobile files: ' + ', '.join(stale))
    print('PASS: 15 mobile homepages and device buttons match desktop sources' if check else 'Built 15 mobile homepages and device buttons')


if __name__ == '__main__':
    main()
